wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.17
    framework: keras
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.12
    start_time: 1655133609
    t:
      1:
      - 2
      - 3
      - 55
      3:
      - 3
      - 8
      - 16
      4: 3.9.12
      5: 0.12.17
      8:
      - 5
      10:
      - 9
batch_size:
  desc: null
  value: 16
epochs:
  desc: null
  value: 25
