wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.17
    framework: keras
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.12
    start_time: 1655197019
    t:
      1:
      - 2
      - 3
      - 55
      3:
      - 16
      4: 3.9.12
      5: 0.12.17
      8:
      - 5
batch_size:
  desc: null
  value: 16
dense:
  desc: null
  value: 64
dropout:
  desc: null
  value: 0.3
epochs:
  desc: null
  value: 20
num_features_l1:
  desc: null
  value: 16
num_features_l2:
  desc: null
  value: 32
num_features_l3:
  desc: null
  value: 64
num_features_l4:
  desc: null
  value: 128
