wandb_version: 1

batch_size:
  value: 6
dropout_c:
  value: 0.4
dropout_ga:
  value: 0.15
epochs:
  value: 40
learning_rate:
  value: 0.00075
num_features_c1:
  value: 128
num_features_c2:
  value: 128
num_features_c3:
  value: 128
