wandb_version: 1

batch_size:
  value: 32
dropout_c:
  value: 0.3
dropout_ga:
  value: 0.4
epochs:
  value: 10
learning_rate:
  value: 0.001
num_features_c1:
  value: 128
num_features_c2:
  value: 128
num_features_c3:
  value: 8
