wandb_version: 1

batch_size:
  value: 2
dropout_c:
  value: 0.1
dropout_ga:
  value: 0.3
epochs:
  value: 80
learning_rate:
  value: 0.00075
num_features_c1:
  value: 128
num_features_c2:
  value: 64
num_features_c3:
  value: 128
