wandb_version: 1

batch_size:
  value: 24
dropout_c:
  value: 0.15
dropout_ga:
  value: 0.05
epochs:
  value: 20
learning_rate:
  value: 0.00075
num_features_c1:
  value: 32
num_features_c2:
  value: 32
num_features_c3:
  value: 4
