wandb_version: 1

batch_size:
  value: 64
dense:
  value: 32
dropout:
  value: 0.45
epochs:
  value: 20
learning_rate:
  value: 0.01
num_features_l1:
  value: 16
num_features_l2:
  value: 64
num_features_l3:
  value: 64
num_features_l4:
  value: 16
