wandb_version: 1

batch_size:
  value: 4
dense:
  value: 64
dropout:
  value: 0.3
epochs:
  value: 25
learning_rate:
  value: 0.001
num_features_l1:
  value: 16
num_features_l2:
  value: 128
num_features_l3:
  value: 128
num_features_l4:
  value: 16
