wandb_version: 1

batch_size:
  value: 64
dense:
  value: 16
dropout:
  value: 0.3
epochs:
  value: 15
learning_rate:
  value: 0.01
num_features_l1:
  value: 128
num_features_l2:
  value: 128
num_features_l3:
  value: 128
num_features_l4:
  value: 32
