wandb_version: 1

batch_size:
  value: 4
dropout_c:
  value: 0.2
dropout_ga:
  value: 0.15
epochs:
  value: 10
learning_rate:
  value: 0.0005
num_features_c1:
  value: 32
num_features_c2:
  value: 128
num_features_c3:
  value: 128
num_features_c4:
  value: 64
