wandb_version: 1

batch_size:
  value: 16
dropout_c:
  value: 0.3
dropout_ga:
  value: 0.2
epochs:
  value: 60
learning_rate:
  value: 0.00025
num_features_c1:
  value: 64
num_features_c2:
  value: 128
num_features_c3:
  value: 64
num_features_c4:
  value: 64
