wandb_version: 1

batch_size:
  value: 12
dropout_c:
  value: 0
dropout_ga:
  value: 0
epochs:
  value: 20
learning_rate:
  value: 0.001
num_features_c1:
  value: 4
num_features_c2:
  value: 8
num_features_c3:
  value: 128
