wandb_version: 1

batch_size:
  value: 64
dropout_c:
  value: 0.4
dropout_ga:
  value: 0.15
epochs:
  value: 90
learning_rate:
  value: 0.0005
num_features_c1:
  value: 128
num_features_c2:
  value: 16
num_features_c3:
  value: 32
num_features_c4:
  value: 32
