wandb_version: 1

batch_size:
  value: 4
dropout_c:
  value: 0
dropout_ga:
  value: 0.1
epochs:
  value: 80
learning_rate:
  value: 0.00025
num_features_c1:
  value: 32
num_features_c2:
  value: 16
num_features_c3:
  value: 64
num_features_c4:
  value: 128
