wandb_version: 1

batch_size:
  value: 8
dropout_c:
  value: 0.4
dropout_ga:
  value: 0.1
epochs:
  value: 20
learning_rate:
  value: 0.01
num_features_c1:
  value: 32
num_features_c2:
  value: 128
num_features_c3:
  value: 32
num_features_c4:
  value: 16
