wandb_version: 1

batch_size:
  value: 16
dropout_c1:
  value: 0.1
dropout_c2:
  value: 0.1
dropout_c3:
  value: 0
dropout_c4:
  value: 0
dropout_ga:
  value: 0.2
learning_rate:
  value: 0.001
num_features_c1:
  value: 64
num_features_c2:
  value: 16
num_features_c3:
  value: 64
num_features_c4:
  value: 32
