wandb_version: 1

batch_size:
  value: 6
dropout_c:
  value: 0
dropout_ga:
  value: 0.3
epochs:
  value: 70
learning_rate:
  value: 0.001
num_features_c1:
  value: 16
num_features_c2:
  value: 64
num_features_c3:
  value: 128
num_features_c4:
  value: 64
