wandb_version: 1

batch_size:
  value: 16
dropout_c:
  value: 0.35
dropout_ga:
  value: 0
epochs:
  value: 20
learning_rate:
  value: 0.00025
num_features_c1:
  value: 64
num_features_c2:
  value: 32
num_features_c3:
  value: 16
num_features_c4:
  value: 16
