wandb_version: 1

batch_size:
  value: 2
dropout_c:
  value: 0.2
dropout_ga:
  value: 0.4
epochs:
  value: 80
learning_rate:
  value: 0.005
num_features_c1:
  value: 16
num_features_c2:
  value: 64
num_features_c3:
  value: 64
num_features_c4:
  value: 128
