wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.17
    framework: keras
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.12
    start_time: 1654803397
    t:
      1:
      - 2
      - 3
      - 55
      2:
      - 2
      - 3
      - 55
      3:
      - 3
      - 8
      - 16
      4: 3.9.12
      5: 0.12.17
      8:
      - 5
      10:
      - 9
    visualize:
      conf_mat:
        panel_config:
          fieldSettings:
            Actual: Actual
            Predicted: Predicted
            nPredictions: nPredictions
          panelDefId: wandb/confusion_matrix/v1
          stringSettings:
            title: Confusion Matrix for Validation Data (91.48% Accurate)
          transform:
            name: tableWithLeafColNames
          userQuery:
            queryFields:
            - args:
              - name: runSets
                value: ${runSets}
              fields:
              - fields: []
                name: id
              - fields: []
                name: name
              - fields: []
                name: _defaultColorIndex
              - args:
                - name: tableKey
                  value: conf_mat_table
                fields: []
                name: summaryTable
              name: runSets
        panel_type: Vega2
batch_size:
  desc: null
  value: 16
epochs:
  desc: null
  value: 20
