wandb_version: 1

batch_size:
  value: 8
dropout_c:
  value: 0.3
dropout_ga:
  value: 0
epochs:
  value: 50
learning_rate:
  value: 0.001
num_features_c1:
  value: 16
num_features_c2:
  value: 128
num_features_c3:
  value: 32
num_features_c4:
  value: 128
