wandb_version: 1

batch_size:
  value: 64
dense:
  value: 16
dropout:
  value: 0.45
epochs:
  value: 30
learning_rate:
  value: 0.0005
num_features_l1:
  value: 64
num_features_l2:
  value: 16
num_features_l3:
  value: 64
num_features_l4:
  value: 128
